language: python
python:
  - "2.7"
install:
  - pip install coverage
  - pip install nose
script:
  - python setup.py install
  - nosetests --with-coverage --cover-package=phyltr
before_install:
  pip install codecov
after_success:
  codecov

